# Copy this file to secrets.toml and fill in real values locally (never commit real secrets)
# For Streamlit Cloud: go to app Settings > Secrets and paste the uncommented key=value pairs.

# Google Gemini / Generative AI
GENAI_API_KEY = "AIzaSyClVMaO7D2gfs0pOnRJb4hwdjDAl9BRNK4"

# Optional: direct download URL for model weights if not committing plant_disease_model.pth
# MODEL_URL = "https://drive.google.com/file/d/17NDDF9V8vRs-KTQD8hZyBajcxAoG1ykJ/view?usp=drive_link"
