# Copy this file to secrets.toml and fill in real values locally (never commit real secrets)
# For Streamlit Cloud: go to app Settings > Secrets and paste the uncommented key=value pairs.

# Google Gemini / Generative AI
GENAI_API_KEY = "YOUR_REAL_KEY_HERE"

# Optional: direct download URL for model weights if not committing plant_disease_model.pth
# MODEL_URL = "https://example.com/path/to/plant_disease_model.pth"
